### PR TITLE
Added copy and deepcopy methods to SFrame, SArray, and SGraph.

### PR DESCRIPTION
**Pull request by hoytak**
Resolution of https://github.com/dato-code/SFrame/issues/85.

### CODE REVIEW

**Comment by ylow** [comment]
@hoytak there appears to be a merge conflict. Can you fix up and rebase?

**Comment by hoytak** [comment]
Rebased.  (both PRs appended tests to end of test_sarray)

**Comment by ylow** [comment]
Hmm... it still doesn't want to merge.

**Comment by hoytak** [comment]
Rebased.  Another issue with adding tests to the end of test_sarray.py.

**Pull request merged**
